# Generated by Django 5.1.5 on 2025-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customerrelationtoproduct',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerrelationtoproduct',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='customerrelationtoproduct',
            unique_together={('customer', 'product')},
        ),
    ]
