# Generated by Django 5.1.5 on 2025-01-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_password_remove_employee_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creadted_at',
            new_name='created_at',
        ),
    ]
