# Generated by Django 5.1.5 on 2025-01-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_user_alter_manager_user_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerrelationtoproduct',
            unique_together=set(),
        ),
    ]
