# Generated by Django 5.0.7 on 2025-02-09 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customer_charge_customer_how_much_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
