# Generated by Django 5.0.7 on 2025-03-09 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_new_rating_product_number_of_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Manager', 'Manager')], max_length=20),
        ),
    ]
