# Generated by Django 5.0.7 on 2025-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_content_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='http://localhost:8000/media/logo_krod3So.png', null=True, upload_to=''),
        ),
    ]
