# Generated by Django 5.0.7 on 2025-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='logo_krod3So.png', null=True, upload_to=''),
        ),
    ]
